---

deployment_name: controlplane
web_network_vm_extension: lb
external_url: "http://$external_url"
network_name: private
web_network_name: private
web_vm_type: default
db_vm_type: default
worker_vm_type: default
db_persistent_disk_type: 50GB
worker_ephemeral_disk: 100GB_ephemeral_disk
