- type: replace
  path: /vm_extensions/-
  value:
    name: cfcr-master-cloud-properties
    cloud_properties:
      iam_instance_profile: ((master_iam_instance_profile))
      elbs:
      - ((cfcr_master_target_pool))

- type: replace
  path: /vm_extensions/-
  value:
    name: cfcr-worker-cloud-properties
    cloud_properties:
      iam_instance_profile: ((worker_iam_instance_profile))
